---
# tasks file for KubevirtRepoInfo
- name: Extract the image name
  set_fact:
    operator_image_name: "{{ lookup('env', 'IMAGE_NAME') | default('quay.io/kubevirt/kubevirt-ssp-operator-container:latest', true }}"
- name: Extract the SSP registry
  set_fact:
    ssp_registry: "{{ operator_image_name.rsplit('/', 1)[0] }}"
- name: Show the SSP registry
  debug:
    msg: "{{ ssp_registry }}"
