---
# tasks file for KubevirtRepoInfo
- name: Extract the operator POD info
  k8s_facts:
    api_version: v1
    kind: Pod
    label_selectors:
      - name = kubevirt-ssp-operator
  register: operator_pod
- name: Extract the registry facts
  set_fact:
    operator_image_name: "{{ operator_pod['spec']['containers'][0]['image'] }}"
    repo_info: "{{ dict(['registry', 'image'] | zip(operator_image_name.rsplit('/', 1))) }}"
    ssp_registry: "{{ repo_info['registry'] }}"
    cacheable: true
