---
# tasks file for KubevirtRepoInfo
- name: Extract the operator POD info
  k8s_facts:
    api_version: v1
    kind: Pod
    label_selectors:
      - name = kubevirt-ssp-operator
  register: operator_pod
- name: Extract the image name
  set_fact:
    operator_image_name: "{{ operator_pod['resources'][0]['spec']['containers'][0]['image'] }}"
- name: Extract the SSP registry
  set_fact:
    ssp_registry: "{{ operator_image_name.rsplit('/', 1)[0] }}"
- name: Show the SSP registry
  debug:
    msg: "{{ ssp_registry }}"
