apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubevirttemplatevalidators.ssp.kubevirt.io
spec:
  group: ssp.kubevirt.io
  names:
    kind: KubevirtTemplateValidator
    listKind: KubevirtTemplateValidatorList
    plural: kubevirttemplatevalidators
    singular: kubevirttemplatevalidator
  scope: Namespaced
  version: v1
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            version:
              type: string
            templateValidatorReplicas:
              type: integer
        status:
          type: object