---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubevirtcommontemplatesbundles.ssp.kubevirt.io
spec:
  group: ssp.kubevirt.io
  names:
    kind: KubevirtCommonTemplatesBundle
    listKind: KubevirtCommonTemplatesBundleList
    plural: kubevirtcommontemplatesbundles
    singular: kubevirtcommontemplatesbundle
  scope: Namespaced
  version: v1
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            version:
              type: string
        status:
          type: object

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubevirtmetricsaggregations.ssp.kubevirt.io
spec:
  group: ssp.kubevirt.io
  names:
    kind: KubevirtMetricsAggregation
    listKind: KubevirtMetricsAggregationList
    plural: kubevirtmetricsaggregations
    singular: kubevirtmetricsaggregation
  scope: Namespaced
  version: v1
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            version:
              type: string
        status:
          type: object
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubevirtnodelabellerbundles.ssp.kubevirt.io
spec:
  group: ssp.kubevirt.io
  names:
    kind: KubevirtNodeLabellerBundle
    listKind: KubevirtNodeLabellerBundleList
    plural: kubevirtnodelabellerbundles
    singular: kubevirtnodelabellerbundle
  scope: Namespaced
  version: v1
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            version:
              type: string
        status:
          type: object

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubevirttemplatevalidators.ssp.kubevirt.io
spec:
  group: ssp.kubevirt.io
  names:
    kind: KubevirtTemplateValidator
    listKind: KubevirtTemplateValidatorList
    plural: kubevirttemplatevalidators
    singular: kubevirttemplatevalidator
  scope: Namespaced
  version: v1
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            version:
              type: string
            templateValidatorReplicas:
              type: integer
        status:
          type: object