sudo: required
dist: bionic
language: go
go: "1.11"

branches:
  only:
  - master
  - /^v[0-9]/

services:
- docker

jobs:
  include:
  - stage: Build and Deploy
    name: Build and Deploy to GitHub
    if: tag IS present
    before_script: skip
    script: make release "IMAGE_TAG=$TRAVIS_TAG"
    deploy:
      provider: releases
      api_key: "$GITHUB_RELEASE_TOKEN"
      skip_cleanup: true
      overwrite: true
      file_glob: true
      file:
      - _out/kubevirt-ssp-operator.yaml
      - _out/kubevirt-ssp-operator-cr.yaml
      - _out/kubevirt-ssp-operator-crd.yaml
      name: $TRAVIS_TAG
      on:
        tags: true
        branch: master
        repo: $TRAVIS_REPO_SLUG
