---
# tasks file for KubevirtTemplateValidator
- name: Extract the operator POD info
  k8s_facts:
    api_version: v1
    kind: Pod
    label_selectors:
      - name = kubevirt-ssp-operator
  register: operator_pod
- name: Extract the POD registry
  set_fact:
    operator_image_name: "{{ operator_pod['spec']['containers'][0]['image'] }}"
- name: parse image info
  set_fact:
    repo_info: "{{ dict(['registry', 'image'] | zip(operator_image_name.rsplit('/', 1))) }}"
- name: Set template:view role
  k8s:
    state: present
    definition: "{{ lookup('template', 'template-view-role.yaml.j2') }}"
- name: Create the service
  k8s:
    state: present
    definition: "{{ lookup('template', 'service.yaml.j2') }}"
# per https://docs.okd.io/latest/dev_guide/secrets.html#service-serving-certificate-secrets
# *every* pod in the cluster has access to the service-ca.crt, so we can safely use
# the one inside the operator POD
- name: Extract the CA bundle
  set_fact:
    cabundle: "{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt') | b64encode }}"
- name: Register the webhook
  k8s:
    state: present
    definition: "{{ lookup('template', 'webhook.yaml.j2') }}"
