apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubevirtmetricsaggregations.ssp.kubevirt.io
spec:
  group: ssp.kubevirt.io
  names:
    kind: KubevirtMetricsAggregation
    listKind: KubevirtMetricsAggregationList
    plural: kubevirtmetricsaggregations
    singular: kubevirtmetricsaggregation
  scope: Namespaced
  version: v1
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            version:
              type: string
        status:
          type: object
