apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubevirtmetricscollectors.kubevirt.io
spec:
  group: kubevirt.io
  names:
    kind: KubevirtMetricsCollector
    listKind: KubevirtMetricsCollectorList
    plural: kubevirtmetricscollectors
    singular: kubevirtmetricscollector
  scope: Namespaced
  version: v1
  subresources:
    status: {}

