apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubevirtcommontemplatesbundles.kubevirt.io
spec:
  group: kubevirt.io
  names:
    kind: KubevirtCommonTemplatesBundle
    listKind: KubevirtCommonTemplatesBundleList
    plural: kubevirtcommontemplatebundles
    singular: kubevirtcommontemplatebundle
  scope: Namespaced
  version: v1
  subresources:
    status: {}

