apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubevirtnodelabellerbundles.ssp.kubevirt.io
spec:
  group: ssp.kubevirt.io
  names:
    kind: KubevirtNodeLabellerBundle
    listKind: KubevirtNodeLabellerBundleList
    plural: kubevirtnodelabellerbundles
    singular: kubevirtnodelabellerbundle
  scope: Namespaced
  version: v1
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            version:
              type: string
        status:
          type: object

