---
- name: Create the node labeller roles
  k8s:
    state: present
    definition: "{{ lookup('template', '/opt/ansible/roles/KubevirtNodeLabeller/templates/kubevirt-node-labeller-roles.yaml.j2') }}"


- name: Create the node labeller daemon set
  k8s:
    state: present
    definition: "{{ lookup('template', '/opt/ansible/roles/KubevirtNodeLabeller/templates/kubevirt-node-labeller-ds.yaml.j2') }}"
  register: nl

- name: "Wait for the node-labeller to start"
  k8s_facts:
    kind: "{{ nl.result.kind }}"
    namespace: "{{ nl.result.metadata.namespace }}"
    api_version: "{{ nl.result.apiVersion }}"
    name: "{{ nl.result.metadata.name }}"
  register: nl_status
  retries: 300
  delay: 10
  until:  nl_status.resources[0].status.currentNumberScheduled == nl_status.resources[0].status.numberReady |default(false)
  when: not wait


