apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevirt-ssp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubevirt-ssp-operator
  template:
    metadata:
      labels:
        name: kubevirt-ssp-operator
    spec:
      serviceAccountName: kubevirt-ssp-operator
      containers:
        - name: kubevirt-ssp-operator
          #FIXME Replace this with the built image name
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WATCH_NAMESPACE
              value: ""
            - name: KVM_INFO_TAG
              value: ""
            - name: VALIDATOR_TAG
              value: ""
            - name: VIRT_LAUNCHER_TAG
              value: ""
            - name: NODE_LABELLER_TAG
              value: ""
            - name: CPU_PLUGIN_TAG
              value: ""
            - name: OPERATOR_NAME
              value: "kubevirt-ssp-operator"
