kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubevirt-ssp-operator
subjects:
- kind: ServiceAccount
  name: kubevirt-ssp-operator
  namespace: default 
roleRef:
  kind: ClusterRole
  name: kubevirt-ssp-operator
  apiGroup: rbac.authorization.k8s.io
