---
# tasks file for KubevirtCommonTemplatesBundle
- name: Install VM templates
  k8s:
    state: present
    namespace: "{{ meta.namespace }}"
    definition: "{{ item | from_yaml }}"
  with_items: "{{ lookup('file', 'common-templates-'+ version +'.yaml').split('\n---\n') | select('search', '(^|\n)[^#]') | list }}"
  register: ct_status

- name: "Count all new templates in file"
  set_fact:
    new_templates: "{{ lookup('file', 'common-templates-'+ version +'.yaml').split('\n---\n') | select('search', '(^|\n)[^#]') | list | length }}"


- name: "Set label"
  set_fact:
    label: "template.kubevirt.io/version={{ version }}"
  
- name: "Get all templates"
  set_fact:
    deployed_templates_after: "{{ lookup('k8s', api_version=ct_status.results[0].result.apiVersion, kind='template', label_selector=label)|length }}"

- name: Set progressing condition
  operator_sdk.util.k8s_status:
    api_version: ssp.kubevirt.io/v1
    kind: KubevirtCommonTemplatesBundle
    name: "{{ meta.name }}"
    namespace: "{{ meta.namespace }}"
    conditions:
    - type: Progressing
      status: "{{ 'True' if new_templates > deployed_templates_after else 'False' }}"
      reason: "progressing"
      message: "Templates progressing."

- name: Set available condition
  operator_sdk.util.k8s_status:
    api_version: ssp.kubevirt.io/v1
    kind: KubevirtCommonTemplatesBundle
    name: "{{ meta.name }}"
    namespace: "{{ meta.namespace }}"
    conditions:
    - type: Available
      status: "{{ 'True' if new_templates <= deployed_templates_after else 'False' }}"
      reason: "available"
      message: "Common templates available."
