---
# tasks file for KubevirtCommonTemplatesBundle
- name: "Get all templates"
  set_fact:
    deployed_templates_before: "{{ lookup('k8s', api_version='template.openshift.io/v1', kind='template') }}"

- name: Install VM templates
  k8s:
    state: present
    namespace: "{{ meta.namespace }}"
    definition: "{{ item | from_yaml }}"
  with_items: "{{ lookup('file', 'common-templates-'+ version +'.yaml').split('\n---\n') | select('search', '(^|\n)[^#]') |list }}"
  register: ct_status

- name: "Get all templates"
  set_fact:
    deployed_templates_after: "{{ lookup('k8s', api_version=ct_status.results[0].result.apiVersion, kind='template') }}"

- name: Set progressing condition
  k8s_status:
    api_version: kubevirt.io/v1
    kind: KubevirtCommonTemplatesBundle
    name: kubevirt-common-template-bundle
    namespace: "{{ meta.namespace }}"
    conditions:
    - type: Progressing
      status: "{{ 'True' if deployed_templates_before|length != deployed_templates_after|length else 'False' }}"
      reason: "progressing"
      message: "Templates progressing."

- name: Set available condition
  k8s_status:
    api_version: kubevirt.io/v1
    kind: KubevirtCommonTemplatesBundle
    name: kubevirt-common-template-bundle
    namespace: "{{ meta.namespace }}"
    conditions:
    - type: Available
      status: "{{ 'True' if deployed_templates_before|length == deployed_templates_after|length else 'False' }}"
      reason: "available"
      message: "Common templates available."
