apiVersion: ssp.kubevirt.io/v1
kind: KubevirtTemplateValidator
metadata:
  name: kubevirt-template-validator
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: testKey
                operator: In
                values:
                  - testValue
          weight: 1
  nodeSelector:
    testKey: testValue
  tolerations:
  - effect: NoSchedule
    key: testKey
    operator: Exists
