apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: kubevirt-ssp
  namespace: marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: kubevirt
  displayName: "KubeVirt SSP"
  publisher: "KubeVirt project"
